### ISSUE TITLE
Uses Private Docker Repo

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/simpatico-platform#2] opened 2018-05-17 10:19 UTC
Hi
 
it seems that the AAC that is deployed to dockerhub is private. 
this results in not being able to pull from docker and set up this platform. 

i suggest that you make it available publicly or use the github repository instead.

**Comment by mirkoperillo** [comment] 2018-05-18 08:00
Hi,

the AAC on dockerhub is a public repository and you can pull image without any authentication.
Maybe the problem is that there isn't the latest tag ( I have to investigate about that), but if you try

`sudo docker pull simpaticoproject/aac:1.1.0` the operation gone alright.

Let me know if this solves your issue

**Comment by breningham** [comment] 2018-05-21 10:44
Nope, if we update the the docker-compose to use the 1.1.0 tag, we get the same issue, that it either does not exist or may require docker login. 

Please review the settings for the AAC.

**Comment by mirkoperillo** [comment] 2018-05-22 08:56
We are not able to reproduce your problem,
please run `sudo docker pull simpaticoproject/aac:1.1.0` and paste the result in the issues

**Comment by breningham** [comment] 2018-05-22 09:13
sorry, just realized,  the problem is that the docker-compose file uses `image: simpatico-project/aac`

while you're asking me to pull `simpaticoproject/aac:1.1.0` 

so the docker-compose needs updating.

**Comment by mirkoperillo** [comment] 2018-05-22 09:15
Fine, I close the issue

**Comment by breningham** [comment] 2018-05-22 09:24
Similiar problem with UPM, i'm re-opening.

**Comment by breningham** [comment] 2018-05-22 09:32
Nevermind, i see that the UPM hasnt been published so needs to be built locally. 

Please add this to the readme file.

**Comment by mirkoperillo** [comment] 2018-05-24 14:28
Sorry you have right.
I put in docker-compose file the references to my local images of upm components instead of the docker hub ones.

Fixed

**Closed as completed by mirkoperillo** 2018-05-24 14:28 UTC
